name: 'sbom4python'
description: 'Generate SBOM for python module/package'
inputs:
  module-name:
    description: 'Python module/package to generate SBOM for'
    required: true
  python-version:
    description: 'Version of Python used'
    required: true
  output-directory:
    description: 'Directory to output to'
    required: false
    default: 'sbom'
outputs:
  changed:
    description: "Did SBOM change?"
    value: ${{ steps.diff-sbom.outputs.changed }}
runs:
  using: "composite"
  steps:
    - name: Generate SBOM
      shell: bash
      run: |
        sbom4python --module "${{ inputs.module-name }}" --output "${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx"
        sbom4python --module "${{ inputs.module-name }}" --sbom cyclonedx --format json --output "${{ inputs.module-name }}-py${{ inputs.python-version }}.json"
    - name: Compare SBOM
      shell: bash
      id: diff-sbom
      # This would fail due to time/date of SBOM generation in SBOM header
      # Therefore ignore first 10 lines of file in comparison which is SBOM header
      run: |
        if [ ! -d sbom ]; then
          echo "changed=first-time" >> $GITHUB_OUTPUT
          exit 0
        fi

        /bin/tail -n +10 "${{ inputs.output-directory }}/${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx" > orig
        /bin/tail -n +10 "${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx" > new
        echo "changed=$(/bin/diff -q orig new)" >> $GITHUB_OUTPUT
    - name: Display generated SBOM if difference detected
      shell: bash
      if: ${{ steps.diff-sbom.outputs.changed }}
      run: |
        /bin/cat ${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx
    - name: Update existing SBOM if difference detected
      shell: bash
      if: ${{ steps.diff-sbom.outputs.changed }}
      run: |
        mkdir -pv ${{ inputs.output-directory }}/
        cp "${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx" "${{ inputs.output-directory }}/${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx"
        cp "${{ inputs.module-name }}-py${{ inputs.python-version }}.json" "${{ inputs.output-directory }}/${{ inputs.module-name }}-py${{ inputs.python-version }}.json"
