name: 'sbom4python'
description: 'Generate SBOM for python module/package'
inputs:
  module-name:
    description: 'Python module/package to generate SBOM for'
    required: true
  python-version:
    description: 'Version of Python used'
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate SBOM
      shell: bash
      run: |
        sbom4python --module "${{ inputs.module-name }}" --output "${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx"
        sbom4python --module "${{ inputs.module-name }}" --sbom cyclonedx --format json --output "${{ inputs.module-name }}-py${{ inputs.python-version }}.json"
    - name: Compare SBOM
      shell: bash
      id: diff-sbom
      # This would fail due to time/date of SBOM generation in SBOM header
      # Therefore ignore first 10 lines of file in comparison which is SBOM header
      run: |
        if [ ! -d sbom ]; then
          echo "changed=first-time" >> $GITHUB_OUTPUT
          exit 0
        fi

        /bin/tail -n +10 "sbom/${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx" > orig
        /bin/tail -n +10 "${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx" > new
        echo "changed=$(/bin/diff -q orig new)" >> $GITHUB_OUTPUT
    - name: Display generated SBOM if difference detected
      shell: bash
      if: ${{ steps.diff-sbom.outputs.changed }}
      run: |
        /bin/cat ${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx
    - name: Update existing SBOM if difference detected
      shell: bash
      if: ${{ steps.diff-sbom.outputs.changed }}
      run: |
        mkdir -pv sbom/
        cp "${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx" "sbom/${{ inputs.module-name }}-py${{ inputs.python-version }}.spdx"
        cp "${{ inputs.module-name }}-py${{ inputs.python-version }}.json" "sbom/${{ inputs.module-name }}-py${{ inputs.python-version }}.json"
    - name: Create Pull Request
      shell: bash
      if: ${{ steps.diff-sbom.outputs.changed }}
      uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
      with:
        commit-message: "chore: update SBOM for Python ${{ inputs.python-version }}"
        title: "chore: update SBOM for Python ${{ inputs.python-version }}"
        branch: chore-sbom-py${{ inputs.python-version }}
        delete-branch: true
        author: GitHub Actions <actions@github.com>
        add-paths: sbom
